/*
 * YtelAPI.Tests
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Threading.Tasks;
using Newtonsoft.Json.Converters;
using YtelAPI.Standard;
using YtelAPI.Standard.Utilities; 
using YtelAPI.Standard.Http.Client;
using YtelAPI.Standard.Http.Response;
using YtelAPI.Tests.Helpers;
using NUnit.Framework;
using YtelAPI.Standard;
using YtelAPI.Standard.Controllers;
using YtelAPI.Standard.Exceptions;

namespace YtelAPI.Tests
{
    [TestFixture]
    public class SharedShortCodeControllerTest : ControllerTestBase
    {
        /// <summary>
        /// Controller instance (for all tests)
        /// </summary>
        private static SharedShortCodeController controller;

        /// <summary>
        /// Setup test class
        /// </summary>
        [SetUp]
        public static void SetUpClass()
        {
            controller = GetClient().SharedShortCode;
        }

        /// <summary>
        /// Retrieve a list of shortcode assignment associated with your Ytel account. 
        /// </summary>
        [Test]
        public async Task TestTestListShortcodes() 
        {
            // Parameters for the API call
            string shortcode = null;
            int? page = null;
            int? pagesize = null;

            // Perform API call
            string result = null;

            try
            {
                result = await controller.CreateListShortcodesAsync(shortcode, page, pagesize);
            }
            catch(APIException) {};

            // Test response code
            Assert.AreEqual(200, httpCallBackHandler.Response.StatusCode,
                    "Status should be 200");

            // Test headers
            Dictionary<string, string> headers = new Dictionary<string, string>();
            headers.Add("Content-Type", "application/json");

            Assert.IsTrue(TestHelper.AreHeadersProperSubsetOf (
                    headers, httpCallBackHandler.Response.Headers),
                    "Headers should match");

        }

        /// <summary>
        /// Retrieve a list of keywords associated with your Ytel account. 
        /// </summary>
        [Test]
        public async Task TestTestListKeywords() 
        {
            // Parameters for the API call
            int? page = null;
            int? pagesize = null;
            string keyword = null;
            int? shortcode = null;

            // Perform API call
            string result = null;

            try
            {
                result = await controller.CreateListKeywordsAsync(page, pagesize, keyword, shortcode);
            }
            catch(APIException) {};

            // Test response code
            Assert.AreEqual(200, httpCallBackHandler.Response.StatusCode,
                    "Status should be 200");

            // Test headers
            Dictionary<string, string> headers = new Dictionary<string, string>();
            headers.Add("Content-Type", "application/json");

            Assert.IsTrue(TestHelper.AreHeadersProperSubsetOf (
                    headers, httpCallBackHandler.Response.Headers),
                    "Headers should match");

        }

        /// <summary>
        /// List Shortcode Templates by Type 
        /// </summary>
        [Test]
        public async Task TestTestListTemplates() 
        {
            // Parameters for the API call
            string type = null;
            int? page = null;
            int? pagesize = null;
            string shortcode = null;

            // Perform API call
            string result = null;

            try
            {
                result = await controller.CreateListTemplatesAsync(type, page, pagesize, shortcode);
            }
            catch(APIException) {};

            // Test response code
            Assert.AreEqual(200, httpCallBackHandler.Response.StatusCode,
                    "Status should be 200");

            // Test headers
            Dictionary<string, string> headers = new Dictionary<string, string>();
            headers.Add("Content-Type", "application/json");

            Assert.IsTrue(TestHelper.AreHeadersProperSubsetOf (
                    headers, httpCallBackHandler.Response.Headers),
                    "Headers should match");

        }

        /// <summary>
        /// List All Inbound ShortCode 
        /// </summary>
        [Test]
        public async Task TestTestListInboundSMS() 
        {
            // Parameters for the API call
            string datecreated = null;
            int? page = null;
            int? pagesize = null;
            string mfrom = null;
            string shortcode = null;

            // Perform API call
            string result = null;

            try
            {
                result = await controller.CreateListInboundSMSAsync(datecreated, page, pagesize, mfrom, shortcode);
            }
            catch(APIException) {};

            // Test response code
            Assert.AreEqual(200, httpCallBackHandler.Response.StatusCode,
                    "Status should be 200");

            // Test headers
            Dictionary<string, string> headers = new Dictionary<string, string>();
            headers.Add("Content-Type", "application/json");

            Assert.IsTrue(TestHelper.AreHeadersProperSubsetOf (
                    headers, httpCallBackHandler.Response.Headers),
                    "Headers should match");

        }

    }
}